name: AWS-EC2 Instance CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy via SSM
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          comment: Re-deploy book-portal containers
          command: |
            set -e
            cd /home/ubuntu/BOOKPORTAL
            docker compose pull
            docker compose down
            docker compose up -d --pull always
            docker image prune -f
